import assert from 'node:assert/strict';
import fs from 'node:fs';
import {places,seeds,makeOrder,planRoute,tick,receiveOrder,distance,metrics,escape} from './public/core.js';
assert.equal(distance(places[0],places[0]),0);
assert.ok(distance(places[0],places[1])>10);
assert.equal(escape('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;');
const initial=seeds();assert.equal(initial.length,2);assert.notEqual(initial[0].role,initial[1].role);
const d={type:'Máu',title:'Test',from:places[0],to:places[1],weight:1,cold:true,priority:'Khẩn cấp',recipient:'Demo'};
assert.equal(planRoute(d).mode,'uav');assert.equal(planRoute({...d,weight:10}).mode,'road');assert.equal(planRoute({...d,to:{lat:23,lng:105}}).mode,'road');
const o=makeOrder(d,'facility');o.alert=true;assert.equal(tick(o),false);assert.equal(o.progress,0);o.alert=false;
for(let i=0;i<200;i++)tick(o);
assert.equal(o.step,3);assert.equal(o.progress,100);assert.equal(metrics(o).eta,0);assert.ok(o.events.length>=4);assert.ok(o.temperatures.length<=24);
assert.match(receiveOrder(o,'000000'),/chưa đúng/);assert.equal(o.step,3);
assert.match(receiveOrder(o,o.otp,o.otpExpires+1),/hết hạn/);
assert.equal(receiveOrder(o,o.otp),null);assert.equal(o.step,4);assert.ok(o.pod);assert.equal(tick(o),false);
const cancelled=makeOrder(d,'personal');cancelled.cancelled=true;assert.equal(tick(cancelled),false);assert.match(receiveOrder(cancelled,cancelled.otp),/chưa đến/);
for(const f of fs.readdirSync('public'))if(/\.(js|html|css)$/.test(f))assert.ok(!/maps\.googleapis\.com|GOOGLE_MAPS_BROWSER_KEY/.test(fs.readFileSync('public/'+f,'utf8')),'No Google Maps dependency: '+f);
const worker=(await import('./dist/server/index.js')).default;
let r=await worker.fetch(new Request('https://app.test/api/map-config'),{});const mapConfig=await r.json();assert.match(mapConfig.tileUrl,/\/api\/tiles/);assert.match(mapConfig.fallbackTileUrl,/openstreetmap/);assert.match(mapConfig.searchUrl,/nominatim/);assert.equal(r.headers.get('Cache-Control'),'no-store');
r=await worker.fetch(new Request('https://app.test/api/tiles/30/0/0.png'),{});assert.equal(r.status,400);
r=await worker.fetch(new Request('https://app.test/'),{});assert.equal(r.status,200);assert.match(await r.text(),/manifest.webmanifest/);
r=await worker.fetch(new Request('https://app.test/sw.js'),{});assert.equal(r.headers.get('Service-Worker-Allowed'),'/');
r=await worker.fetch(new Request('https://app.test/icon-192.png'),{});assert.equal(r.status,200);assert.equal(r.headers.get('Content-Type'),'image/png');
r=await worker.fetch(new Request('https://app.test/missing'),{});assert.equal(r.status,404);
console.log('PASS: role seeds, route calculation, UAV/road selection, alerts, full timeline, OTP invalid/expired/valid, cancellation, POD, OpenStreetMap config, Worker responses, PWA assets.');
